import { defineConfig } from "@rslib/core";

/**
 * Node 内置模块清单，**写死在这里而不是 `import { builtinModules } from "node:module"`**。
 *
 * 两个理由，第二个才是决定性的：
 *
 * ① 审核告警：Obsidian 的社区插件审核器把任何 `node:*` 导入都判为「移动端不可用」
 *    （`rslib.config.ts` 是构建脚本、根本不会进产物，但审核器扫的是源码文本，不看用途）。
 *
 * ② **`builtinModules` 本身是构建期的循环依赖**：rslib 用 esbuild 打包，而 esbuild 要
 *    先解析本文件才能知道 externals 是什么 —— 此时 `node:module` 的求值时机取决于
 *    rslib 是「先加载配置再启动 esbuild」还是「在 esbuild 的插件钩子里加载配置」。
 *    写死之后这条依赖彻底消失，配置的求值不再依赖任何 Node API。
 *
 * 清单取自 Node 20（与 CI 的 `node-version: 20` 对齐），已滤掉 `_` 前缀的私有模块与
 * `node:` 前缀形式（esbuild 的 externals 匹配的是裸名，`node:fs` 这种写法由 esbuild
 * 自己识别，不需要在这里列）。**新增内置模块时这里不用跟着改** —— 本插件只用
 * `Buffer` / `TextEncoder` 这类全局对象，一个 `node:*` 都不导入，这份清单的作用是
 * 「万一将来引入了，别把它打进产物」。
 */
const NODE_BUILTINS = [
  "assert",
  "assert/strict",
  "async_hooks",
  "buffer",
  "child_process",
  "cluster",
  "console",
  "constants",
  "crypto",
  "dgram",
  "diagnostics_channel",
  "dns",
  "dns/promises",
  "domain",
  "events",
  "fs",
  "fs/promises",
  "http",
  "http2",
  "https",
  "inspector",
  "inspector/promises",
  "module",
  "net",
  "os",
  "path",
  "path/posix",
  "path/win32",
  "perf_hooks",
  "process",
  "punycode",
  "querystring",
  "readline",
  "readline/promises",
  "repl",
  "stream",
  "stream/consumers",
  "stream/promises",
  "stream/web",
  "string_decoder",
  "sys",
  "timers",
  "timers/promises",
  "tls",
  "trace_events",
  "tty",
  "url",
  "util",
  "util/types",
  "v8",
  "vm",
  "wasi",
  "worker_threads",
  "zlib",
];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig({
  source: {
    entry: {
      main: "./src/main.ts",
    },
  },
  lib: [
    {
      format: "cjs",
      bundle: true,
      syntax: "es2018",
      autoExternal: false,
      banner: {
        js: banner,
      },
      output: {
        externals: [
          "obsidian",
          "electron",
          "@codemirror/autocomplete",
          "@codemirror/collab",
          "@codemirror/commands",
          "@codemirror/language",
          "@codemirror/lint",
          "@codemirror/search",
          "@codemirror/state",
          "@codemirror/view",
          "@lezer/common",
          "@lezer/highlight",
          "@lezer/lr",
          ...NODE_BUILTINS,
        ],
        distPath: {
          root: ".",
        },
        cleanDistPath: false,
        minify: {
          js: true,
        },
        filename: {
          js: "main.js",
        },
      },
    },
  ],
});
